### PR TITLE
Refactoring to improve test reliability

### PR DESCRIPTION
**Pull request by execut**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by execut** [comment]
@terabytesoftw @samdark All fine? Is there anything wrong?

**Comment by terabytesoftw** [comment]
I have not reviewed it because I am changing db and implementations, I broke bc, which I think will affect here, as soon as I finish I will do it, I don't need much :).

**Comment by execut** [comment]
> I have not reviewed it because I am changing db and implementations, I broke bc, which I think will affect here, as soon as I finish I will do it, I'm almost done :).

Ok, then I'm waiting, thanks for the answer

**Comment by samdark** [comment]
Can't be applied anymore. @vjik took care about tests.

Sorry for not taking your contribution in the end. And thanks for it.

**Pull request closed without merging**
