### PR TITLE
Use View::class for console.

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by samdark** [comment]
@terabytesoftw please resolve conflicts.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Please remove/ignore tests/Data/yiitest.sq3

**Comment by terabytesoftw** [comment]
> Please remove/ignore tests/Data/yiitest.sq3

Done.

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
