### PR TITLE
Fix #31: Introduce RevertibleMigrationInterface

### LINKED ISSUE #31: Identify revertible migrations
Not all migrations can be reverted.
It would be great to specify for a migration (via an interface) if it is revertible.
Advantage of making this explicit is that we can check this before doing the migration.

Scenarios where this could be interesting are things like automatic deployments, migrations that are revertible require a different level of care vs migrations that cannot be reverted.

A simple solution would be to:

- Split `MigrationInterface` into `MigrationInterface` and `RevertibleMigrationInterface`
- Add a `migrate/safe` command that only migrates revertible migrations.

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | #31

### CODE REVIEW

**Comment by terabytesoftw** [comment]
Are you going to merge it?

**Comment by SamMousa** [comment]
What questions?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-db-migration/issues/31#issuecomment-643966069

**Comment by SamMousa** [comment]
Added it. Note that for me dropping a column is not revertible.. If you readd it, there is no data. In this context revertible should mean revertible without data loss. Otherwise everything is revertible; just drop all and rerun migrations to the point in history you want.

**Comment by SamMousa** [comment]
My last comment was aimed at template for dropcolumn migration; I don't think that should be marked revertible since it is not

**Comment by samdark** [comment]
Ah, alright. I'll adjust it.

**Comment by samdark** [comment]
Hmm... it is except data. We can have `down()` and we can apply it.

**Comment by SamMousa** [comment]
Yeah but from that perspective everything is revertible. Just drop the  whole schema and reapply to the point you want... Name one migration that is not revertible if you don't consider data 🤔

**Comment by samdark** [comment]
That may be a separate marker, not an interface...

**Comment by SamMousa** [comment]
Fair enough. But what is the use of the revertible part then?

I tend to not implement a down() if it would cause data destruction... It makes no sense to make that so accessible.

**Comment by samdark** [comment]
Yes, that seems to be up to end user to decide.

**Comment by SamMousa** [comment]
Yeah it is, but we can provide guidance on it..

**Comment by samdark** [comment]
Absolutely but we disagree on the approach here :)

**Pull request merged**
