### PR TITLE
Rename generate/create command to migrate/create

### PR DESCRIPTION
**Pull request by thenotsoft**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by terabytesoftw** [comment]
Tests fails.

**Comment by thenotsoft** [comment]
> Tests fails.

It is not related to this PR, or I'm wrong ?

**Comment by terabytesoftw** [comment]
> > Tests fails.
> 
> It is not related to this PR, or I'm wrong ?

You must change the command in the **tests.**.

```php
1) Yiisoft\Yii\Db\Migration\Tests\Command\Paths\CreateCommandTest::testJunction
Symfony\Component\Console\Exception\CommandNotFoundException: Command "generate/create" is not defined.

Did you mean this?
    migrate/create

/home/runner/work/yii-db-migration/yii-db-migration/vendor/symfony/console/Application.php:675
/home/runner/work/yii-db-migration/yii-db-migration/tests/src/Command/Paths/CreateCommandTest.php:614
/home/runner/work/yii-db-migration/yii-db-migration/tests/src/Command/Paths/CreateCommandTest.php:253
```

**Review by terabytesoftw — APPROVED** [review]

**Comment by samdark** [comment]
Readme should be adjusted.

**Comment by samdark** [comment]
Here's more https://github.com/yiisoft/yii-db-migration/blob/master/src/Service/MigrationService.php#L61

**Review by rustamwin — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
